run:
  go: "1.17"

linters-settings:
  errcheck:
    ignore: '[wW]rite'
  gocyclo:
    min-complexity: 10
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(github.com/Megaputer/go_oauth_phabricator/
      - default
      - blank
      - dot
  gofumpt:
    module-path: github.com/Megaputer/go_oauth_phabricator/
  grouper:
    import-require-single-import: true
    import-require-grouping: true
    const-require-grouping: true
    var-require-single-var: true
  unparam:
    check-exported: true
  wrapcheck:
    ignoreSigs:
      - fmt.Errorf(
      - errors.New(

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exportloopref
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - gofumpt
    - gomnd
    - goprintffuncname
    - gosec
    - grouper
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

output:
  sort-results: true

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
